### ISSUE TITLE
DancingLinks/DancingLinks.cpp

### ISSUE THREAD

**Issue by wxarmstrong** [razimantv/DancingLinks#1]
Hey I had some issues using this code for a set cover problem in a personal project, I fixed it but I think the problem was simply that on line 171, the columns need to be removed in the opposite order, i.e. it should say:

`
for (DancingLinksCell *ptr2 = ptr->left_ptr(); ptr2 != ptr;
ptr2 = ptr2->left_ptr())
`

**Comment by razimantv** [comment]
Oh wow can't believe I missed this. I encountered this bug recently and just fixed it!
